name: EpicParty
version: 1.0.2
main: me.Vark123.EpicParty.Main
author: Vark123
depend: [NBTAPI,EpicRPG]
api-version: 1.18

libraries:
  - io.github.rysefoxx.inventory:RyseInventory-Plugin:1.6.5

commands:
  epicparty:
    aliases: [party, ep, pa, druzyna, team]